/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.cpp
 #	source generated by 4D Plugin Wizard
 #	Project : mapm
 #	author : miyako
 #	2018/09/21
 #
 # --------------------------------------------------------------------------------*/


#include "4DPluginAPI.h"
#include "4DPlugin.h"

#include <chrono>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <memory>
#include <string>
#include <vector>
#include <climits>

std::mutex mutexMapm;

void PluginMain(PA_long32 selector, PA_PluginParameters params)
{
	try
	{
		PA_long32 pProcNum = selector;
		sLONG_PTR *pResult = (sLONG_PTR *)params->fResult;
		PackagePtr pParams = (PackagePtr)params->fParameters;

		CommandDispatcher(pProcNum, pResult, pParams); 
	}
	catch(...)
	{

	}
}

void CommandDispatcher (PA_long32 pProcNum, sLONG_PTR *pResult, PackagePtr pParams)
{
	switch(pProcNum)
	{
        case kInitPlugin :
        case kServerInitPlugin :
            OnStartup();
            break;
            
        case kDeinitPlugin :
            OnExit();
            break;
            
// --- mapm

		case 1 :
			m_apm_gcd(pResult, pParams);
			break;

		case 2 :
			m_apm_lcm(pResult, pParams);
			break;

		case 3 :
			m_apm_add(pResult, pParams);
			break;

		case 4 :
			m_apm_subtract(pResult, pParams);
			break;

		case 5 :
			m_apm_multiply(pResult, pParams);
			break;

		case 6 :
			m_apm_divide(pResult, pParams);
			break;

		case 7 :
			m_apm_integer_divide(pResult, pParams);
			break;

		case 8 :
			m_apm_integer_div_rem(pResult, pParams);
			break;

		case 9 :
			m_apm_reciprocal(pResult, pParams);
			break;

		case 10 :
			m_apm_factorial(pResult, pParams);
			break;

		case 11 :
			m_apm_floor(pResult, pParams);
			break;

		case 12 :
			m_apm_ceil(pResult, pParams);
			break;

		case 13 :
			m_apm_get_random(pResult, pParams);
			break;

		case 14 :
			m_apm_sqrt(pResult, pParams);
			break;

		case 15 :
			m_apm_cbrt(pResult, pParams);
			break;

		case 16 :
			m_apm_log(pResult, pParams);
			break;

		case 17 :
			m_apm_log10(pResult, pParams);
			break;

		case 18 :
			m_apm_exp(pResult, pParams);
			break;

		case 19 :
			m_apm_pow(pResult, pParams);
			break;

		case 20 :
			m_apm_integer_pow(pResult, pParams);
			break;

		case 21 :
			m_apm_integer_pow_nr(pResult, pParams);
			break;

		case 22 :
			m_apm_sin_cos(pResult, pParams);
			break;

		case 23 :
			m_apm_sin(pResult, pParams);
			break;

		case 24 :
			m_apm_cos(pResult, pParams);
			break;

		case 25 :
			m_apm_tan(pResult, pParams);
			break;

		case 26 :
			m_apm_arcsin(pResult, pParams);
			break;

		case 27 :
			m_apm_arccos(pResult, pParams);
			break;

		case 28 :
			m_apm_arctan(pResult, pParams);
			break;

		case 29 :
			m_apm_arctan2(pResult, pParams);
			break;

		case 30 :
			m_apm_sinh(pResult, pParams);
			break;

		case 31 :
			m_apm_cosh(pResult, pParams);
			break;

		case 32 :
			m_apm_tanh(pResult, pParams);
			break;

		case 33 :
			m_apm_arcsinh(pResult, pParams);
			break;

		case 34 :
			m_apm_arccosh(pResult, pParams);
			break;

		case 35 :
			m_apm_arctanh(pResult, pParams);
			break;

		case 36 :
			m_apm_absolute_value(pResult, pParams);
			break;

		case 37 :
			m_apm_negate(pResult, pParams);
			break;

		case 38 :
			m_apm_round(pResult, pParams);
			break;

		case 39 :
			m_apm_compare(pResult, pParams);
			break;

		case 40 :
			m_apm_sign(pResult, pParams);
			break;

		case 41 :
			m_apm_exponent(pResult, pParams);
			break;

		case 42 :
			m_apm_significant_digits(pResult, pParams);
			break;

		case 43 :
			m_apm_is_integer(pResult, pParams);
			break;

		case 44 :
			m_apm_is_even(pResult, pParams);
			break;

		case 45 :
			m_apm_is_odd(pResult, pParams);
			break;

	}
}

#pragma mark helpers

namespace {

    // RAII owner for an M_APM: m_apm_free runs on every exit path,
    // including when a std::vector/std::string allocation throws.
    struct mapm_deleter {
        void operator()(M_APM m) const { if (m) m_apm_free(m); }
    };
    typedef std::unique_ptr<M_APM_struct, mapm_deleter> mapm_ptr;

    // Frees strings allocated by MAPM (MAPM_MALLOC is malloc in the default build).
    struct c_free_deleter {
        void operator()(char *p) const { free(p); }
    };

    inline mapm_ptr mapm_new() {
        return mapm_ptr(m_apm_init());
    }

    inline mapm_ptr mapm_arg(PackagePtr pParams, uint16_t index) {
        return mapm_ptr(m_apm_from_param_at_index(pParams, index));
    }

    // MAPM corrupts its own heap when given negative decimal places
    // (confirmed under AddressSanitizer in m_apm_pow, m_apm_arctan2,
    // m_apm_integer_pow, m_apm_sin_cos), so every "places" argument is clamped here.
    inline int places_arg(PackagePtr pParams, uint16_t index) {
        int places = int_from_param_at_index(pParams, index);
        return places < 0 ? 0 : places;
    }
}

#pragma mark commands

void m_apm_add(sLONG_PTR *pResult, PackagePtr pParams)
{
    std::lock_guard<std::mutex> lock(mutexMapm);

    mapm_ptr r(mapm_new());
    mapm_ptr a(mapm_arg(pParams, 2));
    mapm_ptr b(mapm_arg(pParams, 3));

    m_apm_add(r.get(), a.get(), b.get());

    m_apm_to_param_at_index(r.get(), pParams, 1);
}

void m_apm_subtract(sLONG_PTR *pResult, PackagePtr pParams)
{
    std::lock_guard<std::mutex> lock(mutexMapm);

    mapm_ptr r(mapm_new());
    mapm_ptr a(mapm_arg(pParams, 2));
    mapm_ptr b(mapm_arg(pParams, 3));

    m_apm_subtract(r.get(), a.get(), b.get());

    m_apm_to_param_at_index(r.get(), pParams, 1);
}

void m_apm_multiply(sLONG_PTR *pResult, PackagePtr pParams)
{
    std::lock_guard<std::mutex> lock(mutexMapm);

    mapm_ptr r(mapm_new());
    mapm_ptr a(mapm_arg(pParams, 2));
    mapm_ptr b(mapm_arg(pParams, 3));

    m_apm_multiply(r.get(), a.get(), b.get());

    m_apm_to_param_at_index(r.get(), pParams, 1);
}

void m_apm_gcd(sLONG_PTR *pResult, PackagePtr pParams)
{
    std::lock_guard<std::mutex> lock(mutexMapm);

    mapm_ptr r(mapm_new());
    mapm_ptr a(mapm_arg(pParams, 2));
    mapm_ptr b(mapm_arg(pParams, 3));

    m_apm_gcd(r.get(), a.get(), b.get());

    m_apm_to_param_at_index(r.get(), pParams, 1);
}

void m_apm_lcm(sLONG_PTR *pResult, PackagePtr pParams)
{
    std::lock_guard<std::mutex> lock(mutexMapm);

    mapm_ptr r(mapm_new());
    mapm_ptr a(mapm_arg(pParams, 2));
    mapm_ptr b(mapm_arg(pParams, 3));

    m_apm_lcm(r.get(), a.get(), b.get());

    m_apm_to_param_at_index(r.get(), pParams, 1);
}

void m_apm_integer_divide(sLONG_PTR *pResult, PackagePtr pParams)
{
    std::lock_guard<std::mutex> lock(mutexMapm);

    mapm_ptr r(mapm_new());
    mapm_ptr a(mapm_arg(pParams, 2));
    mapm_ptr b(mapm_arg(pParams, 3));

    m_apm_integer_divide(r.get(), a.get(), b.get());

    m_apm_to_param_at_index(r.get(), pParams, 1);
}

void m_apm_divide(sLONG_PTR *pResult, PackagePtr pParams)
{
    std::lock_guard<std::mutex> lock(mutexMapm);

    mapm_ptr r(mapm_new());
    int places = places_arg(pParams, 2);
    mapm_ptr a(mapm_arg(pParams, 3));
    mapm_ptr b(mapm_arg(pParams, 4));

    m_apm_divide(r.get(), places, a.get(), b.get());

    m_apm_to_param_at_index(r.get(), pParams, 1);
}

void m_apm_is_even(sLONG_PTR *pResult, PackagePtr pParams)
{
    std::lock_guard<std::mutex> lock(mutexMapm);

    mapm_ptr a(mapm_arg(pParams, 1));

    return_int(pResult, m_apm_is_even(a.get()));
}

void m_apm_is_odd(sLONG_PTR *pResult, PackagePtr pParams)
{
    std::lock_guard<std::mutex> lock(mutexMapm);

    mapm_ptr a(mapm_arg(pParams, 1));

    return_int(pResult, m_apm_is_odd(a.get()));
}

void m_apm_sign(sLONG_PTR *pResult, PackagePtr pParams)
{
    std::lock_guard<std::mutex> lock(mutexMapm);

    mapm_ptr a(mapm_arg(pParams, 1));

    return_int(pResult, m_apm_sign(a.get()));
}

void m_apm_exponent(sLONG_PTR *pResult, PackagePtr pParams)
{
    std::lock_guard<std::mutex> lock(mutexMapm);

    mapm_ptr a(mapm_arg(pParams, 1));

    return_int(pResult, m_apm_exponent(a.get()));
}

void m_apm_significant_digits(sLONG_PTR *pResult, PackagePtr pParams)
{
    std::lock_guard<std::mutex> lock(mutexMapm);

    mapm_ptr a(mapm_arg(pParams, 1));

    return_int(pResult, m_apm_significant_digits(a.get()));
}

void m_apm_is_integer(sLONG_PTR *pResult, PackagePtr pParams)
{
    std::lock_guard<std::mutex> lock(mutexMapm);

    mapm_ptr a(mapm_arg(pParams, 1));

    return_int(pResult, m_apm_is_integer(a.get()));
}

void m_apm_absolute_value(sLONG_PTR *pResult, PackagePtr pParams)
{
    std::lock_guard<std::mutex> lock(mutexMapm);

    mapm_ptr r(mapm_new());
    mapm_ptr a(mapm_arg(pParams, 2));

    m_apm_absolute_value(r.get(), a.get());

    m_apm_to_param_at_index(r.get(), pParams, 1);
}

void m_apm_negate(sLONG_PTR *pResult, PackagePtr pParams)
{
    std::lock_guard<std::mutex> lock(mutexMapm);

    mapm_ptr r(mapm_new());
    mapm_ptr a(mapm_arg(pParams, 2));

    m_apm_negate(r.get(), a.get());

    m_apm_to_param_at_index(r.get(), pParams, 1);
}

void m_apm_factorial(sLONG_PTR *pResult, PackagePtr pParams)
{
    std::lock_guard<std::mutex> lock(mutexMapm);

    mapm_ptr r(mapm_new());
    mapm_ptr a(mapm_arg(pParams, 2));

    m_apm_factorial(r.get(), a.get());

    m_apm_to_param_at_index(r.get(), pParams, 1);
}

void m_apm_floor(sLONG_PTR *pResult, PackagePtr pParams)
{
    std::lock_guard<std::mutex> lock(mutexMapm);

    mapm_ptr r(mapm_new());
    mapm_ptr a(mapm_arg(pParams, 2));

    m_apm_floor(r.get(), a.get());

    m_apm_to_param_at_index(r.get(), pParams, 1);
}

void m_apm_ceil(sLONG_PTR *pResult, PackagePtr pParams)
{
    std::lock_guard<std::mutex> lock(mutexMapm);

    mapm_ptr r(mapm_new());
    mapm_ptr a(mapm_arg(pParams, 2));

    m_apm_ceil(r.get(), a.get());

    m_apm_to_param_at_index(r.get(), pParams, 1);
}

void m_apm_log(sLONG_PTR *pResult, PackagePtr pParams)
{
    std::lock_guard<std::mutex> lock(mutexMapm);

    mapm_ptr r(mapm_new());
    int places = places_arg(pParams, 2);
    mapm_ptr a(mapm_arg(pParams, 3));

    m_apm_log(r.get(), places, a.get());

    m_apm_to_param_at_index(r.get(), pParams, 1);
}

void m_apm_log10(sLONG_PTR *pResult, PackagePtr pParams)
{
    std::lock_guard<std::mutex> lock(mutexMapm);

    mapm_ptr r(mapm_new());
    int places = places_arg(pParams, 2);
    mapm_ptr a(mapm_arg(pParams, 3));

    m_apm_log10(r.get(), places, a.get());

    m_apm_to_param_at_index(r.get(), pParams, 1);
}

void m_apm_round(sLONG_PTR *pResult, PackagePtr pParams)
{
    std::lock_guard<std::mutex> lock(mutexMapm);

    mapm_ptr r(mapm_new());
    int places = places_arg(pParams, 2);
    mapm_ptr a(mapm_arg(pParams, 3));

    m_apm_round(r.get(), places, a.get());

    m_apm_to_param_at_index(r.get(), pParams, 1);
}

void m_apm_reciprocal(sLONG_PTR *pResult, PackagePtr pParams)
{
    std::lock_guard<std::mutex> lock(mutexMapm);

    mapm_ptr r(mapm_new());
    int places = places_arg(pParams, 2);
    mapm_ptr a(mapm_arg(pParams, 3));

    m_apm_reciprocal(r.get(), places, a.get());

    m_apm_to_param_at_index(r.get(), pParams, 1);
}

void m_apm_sqrt(sLONG_PTR *pResult, PackagePtr pParams)
{
    std::lock_guard<std::mutex> lock(mutexMapm);

    mapm_ptr r(mapm_new());
    int places = places_arg(pParams, 2);
    mapm_ptr a(mapm_arg(pParams, 3));

    m_apm_sqrt(r.get(), places, a.get());

    m_apm_to_param_at_index(r.get(), pParams, 1);
}

void m_apm_cbrt(sLONG_PTR *pResult, PackagePtr pParams)
{
    std::lock_guard<std::mutex> lock(mutexMapm);

    mapm_ptr r(mapm_new());
    int places = places_arg(pParams, 2);
    mapm_ptr a(mapm_arg(pParams, 3));

    m_apm_cbrt(r.get(), places, a.get());

    m_apm_to_param_at_index(r.get(), pParams, 1);
}

void m_apm_exp(sLONG_PTR *pResult, PackagePtr pParams)
{
    std::lock_guard<std::mutex> lock(mutexMapm);

    mapm_ptr r(mapm_new());
    int places = places_arg(pParams, 2);
    mapm_ptr a(mapm_arg(pParams, 3));

    m_apm_exp(r.get(), places, a.get());

    m_apm_to_param_at_index(r.get(), pParams, 1);
}

void m_apm_sin(sLONG_PTR *pResult, PackagePtr pParams)
{
    std::lock_guard<std::mutex> lock(mutexMapm);

    mapm_ptr r(mapm_new());
    int places = places_arg(pParams, 2);
    mapm_ptr a(mapm_arg(pParams, 3));

    m_apm_sin(r.get(), places, a.get());

    m_apm_to_param_at_index(r.get(), pParams, 1);
}

void m_apm_cos(sLONG_PTR *pResult, PackagePtr pParams)
{
    std::lock_guard<std::mutex> lock(mutexMapm);

    mapm_ptr r(mapm_new());
    int places = places_arg(pParams, 2);
    mapm_ptr a(mapm_arg(pParams, 3));

    m_apm_cos(r.get(), places, a.get());

    m_apm_to_param_at_index(r.get(), pParams, 1);
}

void m_apm_tan(sLONG_PTR *pResult, PackagePtr pParams)
{
    std::lock_guard<std::mutex> lock(mutexMapm);

    mapm_ptr r(mapm_new());
    int places = places_arg(pParams, 2);
    mapm_ptr a(mapm_arg(pParams, 3));

    m_apm_tan(r.get(), places, a.get());

    m_apm_to_param_at_index(r.get(), pParams, 1);
}

void m_apm_arcsin(sLONG_PTR *pResult, PackagePtr pParams)
{
    std::lock_guard<std::mutex> lock(mutexMapm);

    mapm_ptr r(mapm_new());
    int places = places_arg(pParams, 2);
    mapm_ptr a(mapm_arg(pParams, 3));

    m_apm_arcsin(r.get(), places, a.get());

    m_apm_to_param_at_index(r.get(), pParams, 1);
}

void m_apm_arccos(sLONG_PTR *pResult, PackagePtr pParams)
{
    std::lock_guard<std::mutex> lock(mutexMapm);

    mapm_ptr r(mapm_new());
    int places = places_arg(pParams, 2);
    mapm_ptr a(mapm_arg(pParams, 3));

    m_apm_arccos(r.get(), places, a.get());

    m_apm_to_param_at_index(r.get(), pParams, 1);
}

void m_apm_arctan(sLONG_PTR *pResult, PackagePtr pParams)
{
    std::lock_guard<std::mutex> lock(mutexMapm);

    mapm_ptr r(mapm_new());
    int places = places_arg(pParams, 2);
    mapm_ptr a(mapm_arg(pParams, 3));

    m_apm_arctan(r.get(), places, a.get());

    m_apm_to_param_at_index(r.get(), pParams, 1);
}

void m_apm_sinh(sLONG_PTR *pResult, PackagePtr pParams)
{
    std::lock_guard<std::mutex> lock(mutexMapm);

    mapm_ptr r(mapm_new());
    int places = places_arg(pParams, 2);
    mapm_ptr a(mapm_arg(pParams, 3));

    m_apm_sinh(r.get(), places, a.get());

    m_apm_to_param_at_index(r.get(), pParams, 1);
}

void m_apm_cosh(sLONG_PTR *pResult, PackagePtr pParams)
{
    std::lock_guard<std::mutex> lock(mutexMapm);

    mapm_ptr r(mapm_new());
    int places = places_arg(pParams, 2);
    mapm_ptr a(mapm_arg(pParams, 3));

    m_apm_cosh(r.get(), places, a.get());

    m_apm_to_param_at_index(r.get(), pParams, 1);
}

void m_apm_tanh(sLONG_PTR *pResult, PackagePtr pParams)
{
    std::lock_guard<std::mutex> lock(mutexMapm);

    mapm_ptr r(mapm_new());
    int places = places_arg(pParams, 2);
    mapm_ptr a(mapm_arg(pParams, 3));

    m_apm_tanh(r.get(), places, a.get());

    m_apm_to_param_at_index(r.get(), pParams, 1);
}

void m_apm_arcsinh(sLONG_PTR *pResult, PackagePtr pParams)
{
    std::lock_guard<std::mutex> lock(mutexMapm);

    mapm_ptr r(mapm_new());
    int places = places_arg(pParams, 2);
    mapm_ptr a(mapm_arg(pParams, 3));

    m_apm_arcsinh(r.get(), places, a.get());

    m_apm_to_param_at_index(r.get(), pParams, 1);
}

void m_apm_arccosh(sLONG_PTR *pResult, PackagePtr pParams)
{
    std::lock_guard<std::mutex> lock(mutexMapm);

    mapm_ptr r(mapm_new());
    int places = places_arg(pParams, 2);
    mapm_ptr a(mapm_arg(pParams, 3));

    m_apm_arccosh(r.get(), places, a.get());

    m_apm_to_param_at_index(r.get(), pParams, 1);
}

void m_apm_arctanh(sLONG_PTR *pResult, PackagePtr pParams)
{
    std::lock_guard<std::mutex> lock(mutexMapm);

    mapm_ptr r(mapm_new());
    int places = places_arg(pParams, 2);
    mapm_ptr a(mapm_arg(pParams, 3));

    m_apm_arctanh(r.get(), places, a.get());

    m_apm_to_param_at_index(r.get(), pParams, 1);
}

void m_apm_arctan2(sLONG_PTR *pResult, PackagePtr pParams)
{
    std::lock_guard<std::mutex> lock(mutexMapm);

    mapm_ptr r(mapm_new());
    int places = places_arg(pParams, 2);
    mapm_ptr a(mapm_arg(pParams, 3));
    mapm_ptr b(mapm_arg(pParams, 4));

    m_apm_arctan2(r.get(), places, a.get(), b.get());

    m_apm_to_param_at_index(r.get(), pParams, 1);
}

void m_apm_pow(sLONG_PTR *pResult, PackagePtr pParams)
{
    std::lock_guard<std::mutex> lock(mutexMapm);

    mapm_ptr r(mapm_new());
    int places = places_arg(pParams, 2);
    mapm_ptr a(mapm_arg(pParams, 3));
    mapm_ptr b(mapm_arg(pParams, 4));

    m_apm_pow(r.get(), places, a.get(), b.get());

    m_apm_to_param_at_index(r.get(), pParams, 1);
}

void m_apm_integer_div_rem(sLONG_PTR *pResult, PackagePtr pParams)
{
    std::lock_guard<std::mutex> lock(mutexMapm);

    mapm_ptr quotient(mapm_new());
    mapm_ptr remainder(mapm_new());
    mapm_ptr a(mapm_arg(pParams, 3));
    mapm_ptr b(mapm_arg(pParams, 4));

    m_apm_integer_div_rem(quotient.get(), remainder.get(), a.get(), b.get());

    m_apm_to_param_at_index(quotient.get(), pParams, 1);
    m_apm_to_param_at_index(remainder.get(), pParams, 2); // was: quotient written twice
}

void m_apm_compare(sLONG_PTR *pResult, PackagePtr pParams)
{
    std::lock_guard<std::mutex> lock(mutexMapm);

    mapm_ptr a(mapm_arg(pParams, 1));
    mapm_ptr b(mapm_arg(pParams, 2));

    return_int(pResult, m_apm_compare(a.get(), b.get()));
}

void m_apm_get_random(sLONG_PTR *pResult, PackagePtr pParams)
{
    std::lock_guard<std::mutex> lock(mutexMapm);

    mapm_ptr r(mapm_new());

    m_apm_get_random(r.get());

    m_apm_to_param_at_index(r.get(), pParams, 1);
}

void m_apm_integer_pow(sLONG_PTR *pResult, PackagePtr pParams)
{
    std::lock_guard<std::mutex> lock(mutexMapm);

    mapm_ptr r(mapm_new());
    int places = places_arg(pParams, 2);
    mapm_ptr a(mapm_arg(pParams, 3));
    int mexp = int_from_param_at_index(pParams, 4);

    m_apm_integer_pow(r.get(), places, a.get(), mexp);

    m_apm_to_param_at_index(r.get(), pParams, 1);
}

void m_apm_integer_pow_nr(sLONG_PTR *pResult, PackagePtr pParams)
{
    std::lock_guard<std::mutex> lock(mutexMapm);

    mapm_ptr r(mapm_new());
    mapm_ptr a(mapm_arg(pParams, 2));
    int mexp = int_from_param_at_index(pParams, 3);

    m_apm_integer_pow_nr(r.get(), a.get(), mexp);

    m_apm_to_param_at_index(r.get(), pParams, 1);
}

void m_apm_sin_cos(sLONG_PTR *pResult, PackagePtr pParams)
{
    std::lock_guard<std::mutex> lock(mutexMapm);

    mapm_ptr sin_r(mapm_new());
    mapm_ptr cos_r(mapm_new());
    int places = places_arg(pParams, 3);
    mapm_ptr a(mapm_arg(pParams, 4));

    m_apm_sin_cos(sin_r.get(), cos_r.get(), places, a.get());

    m_apm_to_param_at_index(sin_r.get(), pParams, 1);
    m_apm_to_param_at_index(cos_r.get(), pParams, 2); // was: never returned
}

// ------------------------------------- mapm -------------------------------------

#pragma mark -

void OnStartup()
{
    std::lock_guard<std::mutex> lock(mutexMapm);

    long long t = (long long)std::chrono::duration_cast<std::chrono::milliseconds>(
        std::chrono::system_clock::now().time_since_epoch()).count();

    char buf[32];
    snprintf(buf, sizeof(buf), "%lld", t);
    m_apm_set_random_seed(buf);
}

void OnExit()
{
    std::lock_guard<std::mutex> lock(mutexMapm);

    m_apm_free_all_mem();
}

#pragma mark -

void m_apm_to_param_at_index(M_APM mapm, PackagePtr pParams, uint16_t index)
{
    if(!index) return;

    // Show every significant digit, no trailing zeros after the point, no point for integers.
    // m_apm_to_fixpt_stringexp sizes its own buffer (the previous hand-computed size
    // ignored positive exponents and overflowed on any integer with trailing zeros, e.g. 1440).
    long long digits = (long long)m_apm_significant_digits(mapm) - (long long)m_apm_exponent(mapm) - 1;
    int places = (m_apm_is_integer(mapm) || digits < 0) ? 0 : (digits > INT_MAX ? INT_MAX : (int)digits);

    std::unique_ptr<char, c_free_deleter> s(m_apm_to_fixpt_stringexp(places, mapm, '.', 0, 0));
    if(!s) return; // allocation failed inside MAPM; leave the 4D variable untouched

    // The result only ever contains '-', '0'-'9' and '.', so widening each byte is an exact UTF-16 conversion.
    size_t len = strlen(s.get());
    std::vector<PA_Unichar> u(s.get(), s.get() + len);
    u.push_back(0);

    PA_SetUnistring((PA_Unistring *)(pParams[index - 1]), &u[0]);
}

void return_int(sLONG_PTR *pResult, int value)
{
    *(PA_long32 *) pResult = (PA_long32)value;
}

int int_from_param_at_index(PackagePtr pParams, uint16_t index)
{
    int value = 0;

    if(index)
    {
        value = (int)*(PA_long32 *)(pParams[index - 1]);
    }
    return value;
}

M_APM m_apm_from_param_at_index(PackagePtr pParams, uint16_t index)
{
    mapm_ptr mapm(mapm_new()); // zero by default

    if(index)
    {
        PA_Unistring *str = (PA_Unistring *)(pParams[index - 1]);

        if(str && str->fString && str->fLength > 0)
        {
            // A valid MAPM number is pure ASCII. Text containing any non-ASCII
            // character cannot be a number and is left as zero.
            std::string s;
            s.reserve((size_t)str->fLength);
            bool ascii = true;
            for(PA_long32 i = 0; i < str->fLength; ++i)
            {
                PA_Unichar c = str->fString[i];
                if(c >= 0x80) { ascii = false; break; }
                s.push_back((char)c);
            }
            if(ascii)
            {
                m_apm_set_string(mapm.get(), &s[0]); // MAPM copies the input before parsing it
            }
        }
    }
    return mapm.release();
}
